[project]
name = "dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.42.34",
    "botocore[crt]>=1.42.34",
    "json-repair>=0.55.1",
    "markitdown>=0.0.2",
]
